# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apivertx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apivertyotros.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5bd3cab7826e41bbb8971ffd2e3a3163 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dcbf00dde9c24a49a02e8918ac90f954 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apivertyotros.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bd3cab7826e41bbb8971ffd2e3a3163 }}/vertx-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apivertx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a1b6666807149c9b1880a19a14e2c55 }}
        images: 'apivertyotros.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bd3cab7826e41bbb8971ffd2e3a3163 }}/vertx-api:${{ github.sha }}'